# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-11 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyXadminPlug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.IntegerField(verbose_name='用户ID')),
                ('StuNum', models.CharField(max_length=20, verbose_name='学号')),
                ('Grade', models.CharField(max_length=10, verbose_name='成绩等级')),
            ],
            options={
                'verbose_name': '自定义表',
                'verbose_name_plural': '自定义表',
            },
        ),
    ]
